/// Flutter icons PrimeVideoIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PrimeVideoIcon
///      fonts:
///       - asset: fonts/PrimeVideoIcon.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class PrimeVideoIcon {
  PrimeVideoIcon._();

  static const _kFontFam = 'PrimeVideoIcon';
  static const _kFontPkg = null;

  static const IconData amazon = IconData(0xf270, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
